[package]
name = "assignment-3-7"
version = "0.1.0"
authors = ["waqas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Ass7 = {path = "../Ass7"}
